name: First Workflow
on: push
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print great Greet
        run: echo "Hello World...PUSH"
      - name: Print bye
        run: |
             echo "bye-bye"
             echo "bye-by-by"
             echo "bye-bye-by-by"
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          node-version: 18
      - name : Install dependencies
        run: npm ci
      
         

